### ISSUE TITLE
Why the 'asyncData' function doesn't work?

### ISSUE THREAD

**Issue by menglingbujie** [nuxt/typescript#241]
**Describe the bug**
Hey guys, I don't understand why the 'asyncData' function doesn't work?
Anybody know that?

In class api 
asyncData(){
console.log("===asyncData"); // no log
}
created(){
console.log("===created"); // display "===created"
}

**Comment by menglingbujie** [comment]
I understand

@Component({
asyncData(){ // here is ok

}
})

export default class A extends Vue{
}

**Comment by kevinmarrec** [comment]
@menglingbujie You can use `nuxt-property-decorator` over `vue-property-decorator` if you want to use Nuxt component options directly in the class instead of component options :

https://github.com/nuxt/typescript/issues/58#issuecomment-523219892

https://github.com/nuxt-community/nuxt-property-decorator/blob/master/src/nuxt-property-decorator.ts#L20

**Comment by menglingbujie** [comment]
> @menglingbujie You can use `nuxt-property-decorator` over `vue-property-decorator` if you want to use Nuxt component options directly in the class instead of component options :
> 
> [#58 (comment)](https://github.com/nuxt/typescript/issues/58#issuecomment-523219892)
> 
> https://github.com/nuxt-community/nuxt-property-decorator/blob/master/src/nuxt-property-decorator.ts#L20
> 
> Ultimately, you can also register hooks like the link above on your own through a Nuxt plugin.

Cool~~ Thx~!

**Comment by menglingbujie** [comment]
@kevinmarrec Cool~~~ Thx~!
