### ISSUE TITLE
[How to]: Create custom build object in nuxt.config.ts?

### ISSUE THREAD

**Issue by The-BigDaddy** [nuxt/typescript#353]
Hello!

So I have a setup for Nuxt already with vanilla Javascript, and I thought I'd try with Typescript for the hell of it. So far, I've had no difficulties. It's pretty easy to understand, up until I get to the `build` part of the configuration.

In the vanilla I had

```javascript
  build: {
    extend (config) {
      config.module.rules.push({
      // blah blah blah stuff mainly for using Markdown for pages
      });
    },
  // some other stuff down here too
  },
```
But it's obvious that's not going to be 1-to-1 with Typescript. I could just be an idiot who doesn't understand some aspects of Typescript (I understand how to use types and interfaces just fine), but I'm not really sure how this would work here. Do I have to create a new instance of `NuxtConfigurationBuild` and pass everything in to that, _then_ put that in `build: {}` or....what?

This is basically what I have

```typescript
import { Configuration } from '@nuxt/types';
import glob from 'glob';
import path from 'path';
import TerserPlugin from 'terser-webpack-plugin';

const baseUrl : string = 'https://the-website.com';

const config: Configuration = {
   buildModules: ['@nuxt/typescript-build'],
   env : {
     baseUrl
   },
   head: {
   // buncha stuff here
   },
   css: [
     '~some-path',
     '~some-other-path'
   ],
   // etc etc.
};
export default config;
```

Sorry if this seems like a stupid question.

**Comment by ShaggyTech** [comment]
I'm not sure exaclty on your specific question but hopefully this can get you started down the right path.

If it's a general question about how to extend webpack here are some links from the docs:
https://nuxtjs.org/faq/extend-webpack/
https://nuxtjs.org/api/configuration-build
https://nuxtjs.org/api/configuration-build#extend

If you want to know how to configure terser-webpack-plugin see here:
https://nuxtjs.org/api/configuration-build#terser

**Example `nuxt.config.ts`**

``` js
import { Configuration } from '@nuxt/types'

const config: Configuration = {
  verbose: true,
  buildModules: ['@nuxt/typescript-build'],
  plugins: ['~/plugins/composition-api.ts'],
  build: {
    terser: {
      parallel: true,
      cache: false,
      sourceMap: false,
      extractComments: {
        filename: 'LICENSES'
      },
      terserOptions: {
        output: {
        comments: /^\**!|@preserve|@license|@cc_on/
      }
    }
    extend (config, { isDev }) {
      if (config.module?.rules) {
        config.module.rules.push(
          {
            test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
            loader: 'file-loader'
          }
        )
        // ... more rules
      }

      // Sets webpack's mode to development if `isDev` is true.
      if (isDev) { config.mode = 'development' }
    }
  }
}

export default config

```

Regarding TypeScript specifically and any errors encountered:


I haven't tried anything beyond this in a typescript project, but it should be the same concept for other build options. I did receive typescript errors when omitting `if (config.module?.rules){}` from the `extend` function.

The only difference from a normal nuxt `build` object and the below are the `if` blocks to guard against errors I received. Typescript was complaining that config.module could possibly be `undefined`.

The above solution implements guards against undefined values by using `if` blocks but I'm sure there are other ways of doing this.  I believe the errors I were seeing were caused by the inability to use null chaining (`something?.somethingElse`) during variable assignments, and thus no way to ensure a defined variable exists to push to.

---

P.S., I learned something new attempting to answer this, so thank you for your stupid question :stuck_out_tongue_winking_eye:

**Comment by The-BigDaddy** [comment]
If it helps, what I'm trying to do is add the ability to use Markdown for pages (posts or anything that isn't the main page) with markdown-it:

The way it looks in my regular `nuxt.config.js` is like so (I still have to clean it up):
```javascript
    extend (config) {
      config.module.rules.push({
        // TODO add frontmatter-markdown-loader if I need to?
        test: /\.md$/,
        include: path.resolve(__dirname, "src/content"), // path is defined elsewhere
        use: [
          { loader: 'raw-loader' },
          {
            loader: 'markdownit-loader',
            options: md, // this is also defined elsewhere 
          }
          // TODO not sure if I need this or not
          // {
          //   loader: "frontmatter-markdown-loader",
          //   options: {
          //     mode: [FMMode.VUE_COMPONENT],
          //     vue: {
          //       root: 'markdown-body'
	        //     },
          //     markdown(body) {
          //       return md.render(body);
          //     }
          //   }
          // }
        ],
      });

```

But I see your solution. 

> I did receive typescript errors when omitting `if (config.module?.rules){}` from the extend function. Typescript was complaining that config.module could possibly be `undefined`. I'll just have to assume you're right about the null

Hmmm yea, same happens to me. Just trying `extend(config) { config.module.rules.push({})}` gives me gripes about `undefined` as well. I guess it's safe to assume you're right about the null chaining.

The rest is pretty easy without any bumps. There are a few options for `TerserPlugin` that Typescript says don't exist, so I don't know if that's a problem or it's because they're redundant when using Typescript.

**Comment by kevinmarrec** [comment]
What you want to do is not related to TypeScript, and about "could possibly be undefined" TypeScript errors, you need to use `!` operator which tells TypeScript the property can't be null or undefined :

`config.module!`
