### ISSUE TITLE
Files written with lang='tsx' doesn't work

### ISSUE THREAD

**Issue by Yama-Tomo** [nuxt/typescript#370]
Files written with lang='tsx' doesn't work since updated to 1.0.0 (and ts-loader updated to 7.0.5)

<img width="1570" alt="screenshots" src="https://user-images.githubusercontent.com/4970917/83656708-d4dece00-a5fa-11ea-8bae-b3e3da0a0419.png">

I checked, and ts-loader was working until 6.2.2

According to the `ts-loader` document,
> Or if you want to use only tsx, just use the appendTsxSuffixTo option only:

I found a workaround to disable `appendTsSuffixTo`

```typescript
// nuxt.config.ts

export default {
  modules: [
    [
      '@nuxt/typescript-build',
      {
        loaders: {
          ts: { appendTsSuffixTo: [] },
        },
      },
    ],
    ..snip..
  ],
  ..snip..
}
```

Is there any other way?

**Comment by kevinmarrec** [comment]
Hi @Yama-Tomo ,

Could you provide a reproduction repository, also can you confirm that forcing `ts-loader` version back to **6.2.2** using https://classic.yarnpkg.com/en/docs/selective-version-resolutions/ (if using `yarn`, dunno about `npm`), fixes the issue ? Cause I don't think it does.

`.tsx` files will work in any case, the issue here is that for `.vue` files with `lang="tsx"`, it doesn't know how to deal with it.

See https://github.com/vuejs/vue-class-component/issues/314 which is more than 1 year old and `ts-loader` was **5.3.3**.

**Comment by Yama-Tomo** [comment]
@kevinmarrec 

- clone the forked repo: https://github.com/Yama-Tomo/typescript
  - **don't run `yarn install` in the root directory**
- checkout `reproduction-tsx-error` branch
- run `cd examples/options-api/minimal/ && yarn && yarn dev`
  - (remove or rename if exists node_modules in the root directory)

　
I'm thinking it might be because I'm configuration both `appendTsSuffixTo` and `appendTsxSuffixTo`.
I made the following changes and it worked fine.

https://github.com/nuxt/typescript/compare/master...Yama-Tomo:disable-appendTsSuffixTo

**Comment by kevinmarrec** [comment]
@Yama-Tomo Indeed, it seems it work for `.vue?lang=ts` even without `appendTsSuffixTo`, maybe it has been natively supported somehow by `ts-loader` ?
