### ISSUE TITLE
Cannot start creating default project.

### ISSUE THREAD

**Issue by StringKe** [nuxt/typescript#441]
I use yarn create nuxt-app to create a default typescript nuxt project, I haven’t modified any code, it can’t start

https://asciinema.org/a/8iWFLgPTDYaaHC8biFhqneNI2

**Comment by StringKe** [comment]
If I switch @nuxt/typescript-build version is 2.0.0 and @nuxt/typescript-runtime version is 1.0.0, project start success ,no errors

**Comment by kevinmarrec** [comment]
@StringKe Alright, sounds to be since upgrade to TypeScript 4.

You need to upgrade `@nuxt/typescript-runtime` to `2.0` to fix it, cause if you keep `1.0.0`, you'll have two versions of TypeScript installed which cause your issue.

I'm gonna fix `create-nuxt-app` so it doesn't happen when generating a new Nuxt TypeScript app.

**Comment by kevinmarrec** [comment]
@StringKe Could you provide a repository with the issue ? Assuming the rror you seem to have something wrong in the styles of your Vue component => `type=style&index=0&lang=less`.

Check your `style` sections

**Comment by kevinmarrec** [comment]
Good :) Will close this issue when `create-nuxt-app` will be released with the dependencies fix.

**Comment by emjimadhu** [comment]
i am really sorry for commenting in closed issue @kevinmarrec I am having almost similar error.

![Screenshot from 2020-09-17 21-22-43](https://user-images.githubusercontent.com/15604962/93495859-37e73d00-f92c-11ea-816d-9dbf24d504bd.png)

i created a fresh project. and my @nuxt/typescript-runtime version is 2.0.0
