### ISSUE TITLE
Cookbook seems to be outdated regarding plugins

### ISSUE THREAD

**Issue by tillsanders** [nuxt/typescript#451]
I tried to integrate my own typescript-based Vue plugin with Nuxt.js, but I soon noticed, that the typings weren't extended correctly. This led to error messages such as:

`Property '$myInjectedFunction' does not exist on type 'CombinedVueInstance<Vue, unknown, unknown, unknown, Readonly<Record<never, any>>>'.Vetur(2339)`

**To Reproduce**
I set up a new nuxt installation and copied [the example from the cookbook](https://typescript.nuxtjs.org/cookbook/plugins.html#iii-combined-inject). Same error message. I uploaded a reproduction: https://github.com/tillsanders/nuxt-ts-cookbook-error

1. Clone, install, etc.
2. Open the start page pages/index.vue in your IDE (tested with VS Code)
3. Take a look at line 35. You should see the Vetur error

**Expected behavior**
Older versions of nuxt (2.0.0) appear to work. I'm still not sure, what's really going wrong, but at least the cookbook seems to be outdated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1533846/95199684-80807080-07dd-11eb-81ec-be0f23dbe156.png)

I can help update the docs, but first someone would need to explain to me, what's wrong :/

**Comment by kevinmarrec** [comment]
It works for me :

![image](https://user-images.githubusercontent.com/25272043/95203332-e3c0d180-07e2-11eb-9ed8-4128faf8b540.png)

![image](https://user-images.githubusercontent.com/25272043/95203358-f0ddc080-07e2-11eb-99c0-23106829924f.png)

So this is has something to do with your editor.

Please notice that sometimes you need to reload VSCode (you can hit F1 & saerch for "Reload Window") so it correctly load types, cause it loads some types at first load through `tsconfig.json` configuration.

You may also need to :
1) Check you're using last Vetur version
2) Use `"vetur.useWorkspaceDependencies": true` in VSCode configuration, so that Vetur use the TypeScript version installed in WorkSpace and not

Your issue probably comes from **2)** cause my guess would be last Veturs ships TypeScript 3 and Nuxt uses TypeSript 4.

**Comment by tillsanders** [comment]
@kevinmarrec Thanks! I was aware of the reload issue, I'm running the latest Vetur version 0.28.0 and have enabled `vetur.useWorkspaceDependencies`. In other words... I have no idea, why this is happening 😅 And also, I have no idea where I haven't looked yet.

**Comment by kevinmarrec** [comment]
@tillsanders Coule be node_modules/yarn.lock issue, dis you try to fresh clone your reproduction repository, install deps and open IDE ?

**Comment by tillsanders** [comment]
@kevinmarrec I think I found the problem. Your idea about a typescript version mismatch pointed me in the direction. Apparently, when `vetur.useWorkspaceDependencies` is enabled, Vetur will use the typescript version of the first project in a workspace. In my case, I had several folders/projects opened. The first depended on typescript 3.9, whereas nuxt depends on 4.0. Because the other project was the first project, Vetur used 3.9, even for my nuxt project. So the solution for now is, to remove the first project from the workspace. (Reload...) and boooom. Works.

While there are probably good reasons for this behaviour, from a usability point of view, this is a big issue of Vetur. Not entirely sure, but I think, it's already on their radar: https://github.com/vuejs/vetur/issues/815

Anyhow. So I was mistaken, this is not an issue of the cookbook. Closing.

Thanks to @kevinmarrec! This cost me several days. I guessed your PayPal. Have a beer on me, mate!
