### ISSUE TITLE
 Cannot find module '....' or its corresponding type declarations.

### ISSUE THREAD

**Issue by victororlyk** [nuxt/typescript#503]
importing files without .vue extension is not working, even if done like said in official [documentaion](https://typescript.nuxtjs.org/guide/setup/)

here is forked official example where I have added basic Logo component plus shim like it is said in docs.
https://codesandbox.io/s/jovial-zhukovsky-8rclu?file=/pages/index.vue

The same thing is going on in my project.
![Screenshot 2021-04-25 at 21 43 38](https://user-images.githubusercontent.com/33072590/116005390-5f635e00-a60f-11eb-8d6a-f92d83863962.png)

I know about this [issue](https://github.com/nuxt/typescript/issues/153) but it is not working

**Comment by danielroe** [comment]
@victororlyk Yes, you need to include the `.vue` extension when you import a Vue SFC. The step you are referring to in the documentation and the issue you linked is so that TypeScript knows what type that import is meant to have. It is not meant to allow you to import a Vue file without its extension.

**Comment by victororlyk** [comment]
@danielroe thanks for answer, but how can I omit adding .vue like in nuxt project with ts.

**Comment by danielroe** [comment]
@victororlyk You will need to add `.vue`.

**Comment by apgapg** [comment]
This issue should be closed as @danielroe provided the correct solution
