### ISSUE TITLE
Plugin not found error

### ISSUE THREAD

**Issue by mya-ake** [nuxt/typescript#72]
**Describe the bug**
The plugins cannot be loaded.

**To Reproduce**
1. Clone repository https://github.com/mya-ake/reproduction-nuxt-ts-2-9
2. Run `yarn dev`
3. See error

**Expected behavior**
Plugin is loaded

**Screenshots**
<img width="554" alt="スクリーンショット 2019-08-22 12 15 12" src="https://user-images.githubusercontent.com/16383815/63483194-87afc680-c4d6-11e9-8f76-962e8ccf9362.png">

**Additional context**

**Comment by edimitchel** [comment]
I got the same error !

**Comment by kevinmarrec** [comment]
@mya-ake I think it's cause you're `srcDir` is `app`, you need to update `tsconfig.json` to tell that `@/*` resolves to `./app/*` instead of `./*` : https://github.com/mya-ake/reproduction-nuxt-ts-2-9/blob/master/tsconfig.json#L21

@edimitchel Are you also using customized `srcDir` ?

This is something that probably should be in documentation (usage of custom srcDir)

**Comment by mya-ake** [comment]
@kevinmarrec 
Sorry, I was committing the wrong tsconfig.
But adding it will result in an error.

An error will occur even if srcDir is missing.
https://github.com/mya-ake/reproduction-nuxt-ts-2-9/tree/flat

**Comment by edimitchel** [comment]
> @edimitchel Are you also using customized `srcDir` ?

Nope, I use the default srcDir (root).

**Comment by edimitchel** [comment]
**By adding `ts-loader` deps it works fine for me**.
It's strange because the typescript nuxt's module have already a deps to ts-loader, but for me, it wasn't resolved properly..

**Comment by mya-ake** [comment]
Really? An error occurred even after installing `ts-loader`.

**Comment by edimitchel** [comment]
> Really? An error occurred even after installing `ts-loader`.

For you ? Strange.. 
I got another issue with the import.. the alias `@` don't work properly.. My code runs good but TS check fails on it..

**Comment by kevinmarrec** [comment]
@mya-ake For your case, the TypeScript build support is not registered cause you have `buildModule` instead of `buildModules` in your configuration.

![image](https://user-images.githubusercontent.com/25272043/63517778-f1889a00-c4ef-11e9-9e50-3d6a9e084b44.png)
https://typescript.nuxtjs.org/guide/setup.html#configuration

**Comment by kevinmarrec** [comment]
@edimitchel Please provide a repository, your issue seems different

**Comment by mya-ake** [comment]
@kevinmarrec 
Oh... I made a mistake. It's working.
I'm sorry for taking the time. It was really helpful. Thank you.

Close this issue.

**Comment by kevinmarrec** [comment]
No problem @mya-ake !

@edimitchel You can create new issue with giving again the context of your issue and a reproduction repository, I'll take a look.

**Comment by edimitchel** [comment]
> EDIT : for the `ts-loader` thing, you may have upgraded and have a broken `node_modules` somehow, try reinstalling fresh dependencies

I did a fresh installation by removing `node_modules` folder and `yarn.lock`.
_____
> @edimitchel You can create new issue with giving again the context of your issue and a reproduction repository, I'll take a look.

Done here #79
